<?php

namespace front\AnnonceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends EntityRepository
{

    public function nonLus($user)
    {
        $query = $this->createQueryBuilder('c');
        $query->join("c.annonce", "a");
        $query->where('a.user=:user')->setParameter('user', $user);
        $query->andWhere('c.lus=:etat')->setParameter('etat', false);
        return $query->getQuery()->getResult();
    }

}
