#danvbe/UserBundle/Resources/services.yml
parameters:
    my_user_provider.class: admin\UserBundle\Security\Core\User\FOSUBUserProvider

services:
    acme_user.registration.form.type:
        class: admin\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: acme_user_registration }
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]