front_service_homepage:
    path:     /annonces/{titre}-{id}
    defaults: { _controller: frontServiceBundle:Default:show }

liste_annonce:
    path:     /annonces/{page}/{type}/{region}/{ville}/{categorie}/{service}/{search}/{orderby}/{desc}
    defaults: { _controller: frontServiceBundle:Default:liste,type:0,region:0,ville:0,categorie:0,service:0,search:'_',orderby:'dateCreation',page:1,desc:'desc' }
    requirements:
        type: 1|2|0
        region:  \d+
        categorie:  \d+
        ville:  \d+
        service:  \d+
        page:  \d+
        desc:  asc|desc
        orderby: prix|titre|dateCreation
Filtre:
    path:     /orderby/{page}/{type}/{region}/{ville}/{categorie}/{service}/{search}/{orderby}/{desc}
    defaults: { _controller: frontServiceBundle:Default:filtre,type:0,region:0,ville:0,categorie:0,service:0,search:'_',orderby:'dateCreation',page:1,desc:'desc' }
    requirements:
        type: 1|2|0
        region:  \d+
        categorie:  \d+
        ville:  \d+
        service:  \d+
        page:  \d+
        desc:  asc|desc
        orderby: prix|titre|dateCreation