ville:
    path:     /
    defaults: { _controller: "adminLocBundle:Ville:index" }

ville_show:
    path:     /{id}/show
    defaults: { _controller: "adminLocBundle:Ville:show" }

ville_new:
    path:     /new
    defaults: { _controller: "adminLocBundle:Ville:new" }

ville_create:
    path:     /create
    defaults: { _controller: "adminLocBundle:Ville:create" }
    requirements: { _method: post }
    
ville_ajax:
    path:     /ville_ajax
    defaults: { _controller: "adminLocBundle:Ville:ajax" }

ville_edit:
    path:     /{id}/edit
    defaults: { _controller: "adminLocBundle:Ville:edit" }

ville_update:
    path:     /{id}/update
    defaults: { _controller: "adminLocBundle:Ville:update" }
    requirements: { _method: post|put }

ville_delete:
    path:     /{id}/delete
    defaults: { _controller: "adminLocBundle:Ville:delete" }
    requirements: { _method: post|delete }
