<?php

namespace Proxies\__CG__\front\AnnonceBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Annonce extends \front\AnnonceBundle\Entity\Annonce implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'id', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'titre', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'texte', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'prix', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'tel1', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'tel2', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'email', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'adresse', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'etat', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'dateCreation', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'dateModification', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'region', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'commentaires', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'ville', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'user', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'services', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'photo1', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'photo2', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'photo3', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'photo4');
        }

        return array('__isInitialized__', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'id', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'titre', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'texte', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'prix', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'tel1', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'tel2', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'email', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'adresse', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'etat', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'dateCreation', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'dateModification', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'region', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'commentaires', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'ville', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'user', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'services', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'photo1', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'photo2', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'photo3', '' . "\0" . 'front\\AnnonceBundle\\Entity\\Annonce' . "\0" . 'photo4');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Annonce $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', array($titre));

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', array());

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTexte($texte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTexte', array($texte));

        return parent::setTexte($texte);
    }

    /**
     * {@inheritDoc}
     */
    public function getTexte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTexte', array());

        return parent::getTexte();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', array($prix));

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', array());

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel1($tel1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel1', array($tel1));

        return parent::setTel1($tel1);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel1', array());

        return parent::getTel1();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel2($tel2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel2', array($tel2));

        return parent::setTel2($tel2);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel2', array());

        return parent::getTel2();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', array($etat));

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', array());

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', array($dateCreation));

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', array());

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModification($dateModification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModification', array($dateModification));

        return parent::setDateModification($dateModification);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModification', array());

        return parent::getDateModification();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegion(\admin\LocBundle\Entity\Region $region = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegion', array($region));

        return parent::setRegion($region);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegion', array());

        return parent::getRegion();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille(\admin\LocBundle\Entity\Ville $ville = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', array($ville));

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', array());

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\admin\UserBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function RemoveAllServices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'RemoveAllServices', array());

        return parent::RemoveAllServices();
    }

    /**
     * {@inheritDoc}
     */
    public function addService(\admin\RefBundle\Entity\Service $services)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addService', array($services));

        return parent::addService($services);
    }

    /**
     * {@inheritDoc}
     */
    public function removeService(\admin\RefBundle\Entity\Service $services)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeService', array($services));

        return parent::removeService($services);
    }

    /**
     * {@inheritDoc}
     */
    public function AService(\admin\RefBundle\Entity\Service $service)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'AService', array($service));

        return parent::AService($service);
    }

    /**
     * {@inheritDoc}
     */
    public function getServices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServices', array());

        return parent::getServices();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto1($photo1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto1', array($photo1));

        return parent::setPhoto1($photo1);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto1', array());

        return parent::getPhoto1();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto2($photo2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto2', array($photo2));

        return parent::setPhoto2($photo2);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto2', array());

        return parent::getPhoto2();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto3($photo3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto3', array($photo3));

        return parent::setPhoto3($photo3);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto3', array());

        return parent::getPhoto3();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto4($photo4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto4', array($photo4));

        return parent::setPhoto4($photo4);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto4', array());

        return parent::getPhoto4();
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadRootDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadRootDir', array());

        return parent::getUploadRootDir();
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadDir', array());

        return parent::getUploadDir();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', array());

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function upload2($ph1, $ph2, $ph3, $ph4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload2', array($ph1, $ph2, $ph3, $ph4));

        return parent::upload2($ph1, $ph2, $ph3, $ph4);
    }

    /**
     * {@inheritDoc}
     */
    public function GetUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'GetUrl', array());

        return parent::GetUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotos', array());

        return parent::getPhotos();
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstPhoto', array());

        return parent::getFirstPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function IsAnnule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'IsAnnule', array());

        return parent::IsAnnule();
    }

    /**
     * {@inheritDoc}
     */
    public function IsEnregistre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'IsEnregistre', array());

        return parent::IsEnregistre();
    }

    /**
     * {@inheritDoc}
     */
    public function ShowEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'ShowEtat', array());

        return parent::ShowEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommentaire(\front\AnnonceBundle\Entity\Commentaire $commentaires)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommentaire', array($commentaires));

        return parent::addCommentaire($commentaires);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommentaire(\front\AnnonceBundle\Entity\Commentaire $commentaires)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommentaire', array($commentaires));

        return parent::removeCommentaire($commentaires);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaires()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaires', array());

        return parent::getCommentaires();
    }

}
